Repository OpenMined/SyMPC, pull requests merged in 2021-06, with the labels that each got.

#205 added codecov
  .github/workflows/tests.yml
Labels: feature

#194 Added Hook method and property -RSTensor
  src/sympc/tensor/replicatedshare_tensor.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: feature

#202 Fixed Point Encoding - RSTensor
  src/sympc/tensor/replicatedshare_tensor.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: feature

#213 Refactored hook method and property -RSTensor
  src/sympc/tensor/replicatedshare_tensor.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: refactor

#136 Add Sigmoid (cheby), Static Methods (stack, cat)
  src/sympc/api.py
  src/sympc/approximations/sigmoid.py
  src/sympc/approximations/tanh.py
  src/sympc/tensor/__init__.py
  src/sympc/tensor/mpc_tensor.py
  src/sympc/tensor/share_tensor.py
  src/sympc/tensor/static.py
  tests/sympc/approximations/sigmoid_test.py
  tests/sympc/tensor/static_test.py
Labels: enhancement, feature

#211 added tests and fixed GradPow, GradMatMul
  src/sympc/tensor/grads/grad_functions.py
  tests/sympc/tensor/grad/grad_functions_test.py
Labels: tests

#207 Test for RSTensor send and get. Also added equal operation for RSTensor
  src/sympc/tensor/replicatedshare_tensor.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: feature

#173 Add smpc argmax
  src/sympc/api.py
  src/sympc/approximations/tanh.py
  src/sympc/tensor/mpc_tensor.py
  src/sympc/tensor/share_tensor.py
  src/sympc/tensor/static.py
  tests/sympc/tensor/static_test.py
Labels: enhancement, feature

#216 Feat/duet in docker container
  duet-docker/Dockerfile
  duet-docker/docker-compose.yml
  duet-docker/owner/Dockerfile
  duet-docker/owner/data-owner-notebook.ipynb
  duet-docker/scientist/Dockerfile
  duet-docker/scientist/data-scientist-notebook.ipynb
Labels: feature

#223 removed old benchmark data
  dev/bench/data.js
Labels: enhancement

#222 Added security_type attribute to protocol
  src/sympc/protocol/falcon/falcon.py
  src/sympc/protocol/fss/fss.py
  src/sympc/protocol/protocol.py
  src/sympc/session/session.py
  tests/sympc/protocol/falcon/falcon_test.py
  tests/sympc/protocol/fss/fss_test.py
  tests/sympc/protocol/protocol_test.py
  tests/sympc/tensor/mpc_tensor_test.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: feature

#220 Distribute shares and reconstruct functionality for RSTensor
  src/sympc/api.py
  src/sympc/session/session.py
  src/sympc/tensor/mpc_tensor.py
  src/sympc/tensor/replicatedshare_tensor.py
  src/sympc/tensor/share_tensor.py
  tests/sympc/protocol/falcon/falcon_test.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: feature

#238 added GradReLU function
  src/sympc/approximations/__init__.py
  src/sympc/tensor/grads/grad_functions.py
  tests/sympc/tensor/grad/grad_functions_test.py
Labels: feature

#232 added forward test
  tests/sympc/tensor/grad/grad_functions_test.py
Labels: tests

#228 Implementation of PRRS(Pseudo-Random Random Share)
  src/sympc/api.py
  src/sympc/session/session.py
  tests/sympc/session/session_test.py
Labels: feature

#241 Fixed reconstruction when torch matrices are a secret and added tests to verify same
  src/sympc/tensor/replicatedshare_tensor.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: bug

#242 Implementation of add/sub operations -RSTensor
  src/sympc/tensor/mpc_tensor.py
  src/sympc/tensor/replicatedshare_tensor.py
  src/sympc/tensor/share_tensor.py
  tests/sympc/tensor/grad/grad_functions_test.py
  tests/sympc/tensor/mpc_tensor_test.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: feature

#229 added backward function test for MPC Tensor
  tests/sympc/tensor/mpc_tensor_test.py
Labels: tests

#195 docs: readme
  README.md
  README.rst
Labels: documentation

#247 Modified RSTensor to use parallel execution
  src/sympc/tensor/replicatedshare_tensor.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
Labels: refactor

#252 Modified allowlist to use absolute paths.
  src/sympc/api.py
  src/sympc/encoder/__init__.py
  src/sympc/protocol/fss/__init__.py
  tests/sympc/session/session_test.py
  tests/sympc/tensor/replicatedshare_tensor_test.py
  tests/sympc/tensor/share_tensor_test.py
Labels: feature, refactor

#262 Fix the crypto provider generation for FSS
  src/sympc/store/crypto_primitive_provider.py
Labels: bug
