Repository OpenMined/SyMPC, pull requests merged in 2021-05, with the labels that each got.

#135 Disable CUDA when using FSS
  src/sympc/protocol/fss/fss.py
Labels: bug

#140 Sort list of MPC Tensors
  src/sympc/algorithms/__init__.py
  src/sympc/algorithms/algorithms.py
  tests/sympc/algorithms/sort_test.py
Labels: feature

#175 added pre-generated primitive notebook
  examples/introduction.ipynb
  examples/using pre-generated primitives.ipynb
Labels: documentation

#174 docs: contributing
  .github/workflows/tests.yml
  CONTRIBUTING.md
Labels: documentation

#189 Initialize FALCON Protocol
  .github/workflows/tests.yml
  src/sympc/api.py
  src/sympc/protocol/__init__.py
  src/sympc/protocol/falcon/__init__.py
  src/sympc/protocol/falcon/falcon.py
  src/sympc/tensor/mpc_tensor.py
  tests/sympc/protocol/falcon/falcon_test.py
Labels: feature

#179 Grad function Conv2d
  src/sympc/api.py
  src/sympc/protocol/beaver/beaver.py
  src/sympc/protocol/spdz/spdz.py
  src/sympc/tensor/__init__.py
  src/sympc/tensor/grads/__init__.py
  src/sympc/tensor/grads/grad_functions.py
  src/sympc/tensor/mpc_tensor.py
  src/sympc/tensor/share_tensor.py
  tests/sympc/tensor/grad/grad_functions_test.py
  tests/sympc/tensor/mpc_tensor_test.py
Labels: feature

#203 Modified NOT_COMPARE attribute in Session class.
  src/sympc/session/session.py
  tests/sympc/tensor/share_tensor_test.py
Labels: bug

#204 added GradFlatten Tests
  src/sympc/api.py
  tests/sympc/tensor/grad/grad_functions_test.py
Labels: tests

#198 added support for GradReshape
  src/sympc/api.py
  src/sympc/tensor/grads/grad_functions.py
  tests/sympc/tensor/grad/grad_functions_test.py
Labels: feature
